config/routes.rb
Rails.application.routes.draw do

  root "users#index"
  resources :expenses, :users    
  resources :sessions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :transactions, dependent: :destroy
    validates :amount, presence: true, numericality: true
    validates :description, uniqueness: {scope: :amount}
    validate :validate_validates
    before_save :check_zero_amount

  private

  def validate_validates
    if description == "validate"
      errors.add(:description, "Checking validate vs validates......using Custom Validation")
    end
    end

  def check_zero_amount 
    if amount <= 0
      errors.add(:amount, "Should be greater than zero..... Using before_save Callback")
      throw :abort
    end
  end

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    # validate :name, custom_method: {scope: :email}
    validates :name, presence: true, uniqueness: true
    has_and_belongs_to_many :expenses 
    # has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user 
    before_action :authenticate_user
    
    # include ExpensesHelper
    
    def current_user 
        @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
    end

    def authenticate_user
        redirect_to new_session_path unless current_user.present?
    end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :update, :destroy]
  before_action :authorize_user, only: [:create, :update, :destroy]
  # before_action :popup_display,only: [:create]
  #before_action :set_expense, only: [:show, :edit, :update, :destroy]
  # before_action :third_filter
  # before_action :first_filter, except: [:create]
  # before_action :second_filter, only: [:new, :create, :index]

  # GET /expenses
  # GET /expenses.json
  def new
    @expense = Expense.new
    # @users = User.all
  end

  def create
    # binding.break
    @expense = Expense.new(expense_params)
    @expense.paid_by = current_user.id
    @expense.expense_type = "Equal"

    friends_ids = params[:expense][:user_ids]

    if @expense.save
      group_size = friends_ids.length-1
      amount_per_head = (@expense.amount)/group_size.to_f
      sender = @expense.paid_by

      split_ids = []

      friends_ids.each do |user_id|
        receiver = user_id.to_i 
        if user_id.present?
          unless sender.equal?(receiver)
            # puts amount_per_head.class 
            # if Transaction.exists?(sender: sender, receiver: receiver)
            #   Transaction.where(sender: sender, receiver: receiver).update_all("amount = amount + #{amount_per_head}")
            # else
            #   Transaction.create(sender: sender, receiver: receiver, amount: amount_per_head) 
            # end
            @expense.transactions.create(sender: sender, receiver: receiver, amount: amount_per_head)
          end
          split_ids << user_id.to_i 
        end

      end

      @expense.user_ids = split_ids

      flash[:alert] = 'New Expense successfully Added!'
      redirect_to expenses_path

    else
        # @expense.errors.full_messages.each do |message|
        #   flash[:alert] = message
        # end
      @expense.errors.full_messages.each do |message|
        puts message
      end
      flash.now[:alert] = @expense.errors.full_messages.join(', ')
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @expense = Expense.find(params[:id])
    @transactions = @expense.transactions
    @payer_id = @expense.paid_by
    @payer_name = User.find(@payer_id).name
  end

  def index
    @expenses = current_user.expenses
    @lene_ka_array = Transaction.where(sender: current_user.id).pluck(:receiver,:amount)
    @dene_ka_array = Transaction.where(receiver: current_user.id).pluck(:sender, :amount)

    @lene_ka_record = array_to_hash @lene_ka_array 
    @dene_ka_record = array_to_hash @dene_ka_array

    @net_balance_record = {}

    @lene_ka_record.each do |key, value|
      if @dene_ka_record[key].present?
        @net_balance_record[key] = value - @dene_ka_record[key] 
      else 
        @net_balance_record[key] = value
      end
    end

    @dene_ka_record.each do |key, value|
      unless @net_balance_record[key].present?
        @net_balance_record[key] = -value
      end
    end

    @balance_ids = []
    @net_balance_record.each do|key,value|
      @balance_ids << key
    end

    @map_id_names = User.where(id: @balance_ids).pluck(:id, :name).to_h
    @result = {}

    @map_id_names.each do|id, name|
      @result[name] = @net_balance_record[id]
    end
    @result

  end

  def destroy
  end

  
  private
  def expense_params
    params.require(:expense).permit(:description, :amount) 
    # binding.break
    # params.require(:expense).permit(:description, :amount, :expense_type)  
  end

  def array_to_hash arr
    result = {}
    arr.each do |nest_array|
      key = nest_array[0]
      value = nest_array[1]
      if result.has_key?(key)
          result[key] += value 
      else
          result[key] = value
      end
    end
    result
  end

  def first_filter
    puts "Calling from first filter"
    Rails.logger.info "Calling from first filter"
  end

  def second_filter
    puts "Calling from second filter"
    Rails.logger.info "Calling from Second filter"
  end

  def third_filter
    puts "Calling from Third filter"
    Rails.logger.info "Calling from third filter"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]
    def new
      # if current_user.present? 
			# 	redirect_to root_path
			# end
      redirect_to users_path if current_user
      @user = User.new
    end
  
    def create
      # binding.break 
      @user = User.find_by(name: params[:user][:name])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to root_path 
      else
        flash[:alert] = "Invalid username or password"
        redirect_to new_session_path
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to root_path
    end
    
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]
  def index
    # binding.break
    @users = User.all 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created successfully"
      redirect_to users_path
    else
      flash[:alert] = "User not created"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
	def calculate_balance(amount, users)
		#return hash of users with balances
	end
	
	def example_helper
		"Example helper usage"
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/create.html.erb
<h1>Expenses#create</h1>
<p>Find me in app/views/expenses/create.html.erb</p>

app/views/expenses/destroy.html.erb
<h1>Expenses#destroy</h1>
<p>Find me in app/views/expenses/destroy.html.erb</p>

app/views/expenses/index.html.erb
<%= link_to "Home Page", root_path%>
<%= button_to "LogOut", session_path(current_user), method: :delete %>
<h2><%= "Hey #{current_user.name}! Welcome to DS SplitWise" %></h2>
<%= button_to "Add Expense", new_expense_path, method: :get %>

<h2>Expense Record</h2>
<ul>
    <% @expenses.each do |expense| %>
        <li><%= link_to expense.description, expense_path(expense) %></li>
    <% end %>

</ul>


<h3> Balance Calculation: </h3>

<ul> 
    <% @result.each do|name, amount| %>
    
        <% if amount < 0 %>
            <li>
            	<%= "You owe #{name} -> #{-amount}"%>
						</li>
        <%elsif amount > 0%>
						<li>
            	<%= "#{name} owe you -> #{amount}"%>
						</li>
        <%else%>
						<li>
            	<%= "You have <No Balance> with #{name}"%>
						</li>
        <%end%>
    
    <%end%>
</ul>



    

app/views/expenses/new.html.erb
<h1><%= current_user.name %> Add your Expense</h1>
<p>Find me in app/views/expenses/new.html.erb</p>


<%= form_with model: @expense do |expense_form| %>
<div> 
	<%= expense_form.label :description, "Description"%>
	<%= expense_form.text_field :description %>
</div>

<div> 
	<%= expense_form.label :amount, "Enter Amount" %>
	<%= expense_form.text_field :amount%>
</div>
 

<!--

<div> 
	<h4> Distribution Type </h4>
	<%= expense_form.radio_button :expense_type, "Equal"%>
	<%= expense_form.label :expense_type_equal, "Equal Distribution"%> <br>
	<%= expense_form.radio_button :expense_type, "Unequal"%>
	<%= expense_form.label :expense_type_unequal, "Unequal Distribution"%><br>
	<%= expense_form.radio_button :expense_type, "Percentage"%>
	<%= expense_form.label :expense_type_percentange, "Percentage Distribution"%>
</div>


<div>
  <h4>Split Among:</h4>
  <% User.order(:name).each do |user| %>
    <%= label_tag "expense_form[user_#{user.id}]", user.name %>
    <%= text_field_tag "expense_form[user_#{user.id}]" %><br>
  <% end %>
</div>

-->

<div>
  <h4>Split Among:</h4>
  <%= expense_form.collection_check_boxes :user_ids, User.order(:name), :id, :name do |b| %>
    <%= b.check_box + b.label %><br>
  <% end %>
</div>



<div>
	<br>
  <%= expense_form.submit "Add Expense"%>
</div>

<%end %>

app/views/expenses/show.html.erb
<table>
	<tr>
		<td>
			Description:
		</td>
		<td>
			<%= @expense.description %>
		</td>
	</tr>

	<tr>
		<td>
			Amount:
		</td>
		<td>
			<%= @expense.amount %>
		</td>
	</tr>

	<tr>
		<td>
			Expense Type:
		</td>
		<td>
			<%= @expense.expense_type %>
		</td>
	</tr>

	<tr>
		<td>
			Bill Paid By:
		</td>
		<td>
			<%= @payer_name %>
		</td>
	</tr>
	
	<tr>
		<td>
			Split Between:
		</td>
		<td>
			<ol>
				<% @expense.users.each do |user| %>

						<% unless user.id.equal?@payer_id %>

							<% if current_user.id == user.id %>
								<li>
									<%= "You -> #{@payer_name} : #{@transactions.where(receiver: user.id).pluck(:amount)}" %>
								</li>
							<%elsif current_user.id == @payer_id%>
								<li>
									<%= "#{user.name} -> You : #{@transactions.where(receiver: user.id).pluck(:amount)}" %>
								</li>
							<%else%>
								<li>
									<%= "#{user.name} -> #{@payer_name} : #{@transactions.where(receiver: user.id).pluck(:amount)}" %>
								</li>
							<%end%>

            <%end%>

				<% end %>
			</ol>
		</td>
	</tr>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>


      <h4><%= notice %></h4>
      <h4 ><%= alert %></h4>
      

    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= link_to "NewUser?", new_user_path %> <br>

<% if current_user %>
    <h1>Welcome <%= current_user.name %> </h1>
    <%= link_to 'LogOut', session_path(current_user), data: {turbo_method: :delete} %> <br>
<%else %>
    <%= link_to 'LogIn', new_session_path%> <br>
<%end%>

<p>Available Users</p>

<ul>
<% @users.each do|user| %>

<li> <%= user.name %> </li>

<% end %>

</ul>

<%= button_to "Expense Record", expenses_path, method: :get%>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_with model: @user do |user_form| %>
	<div> 
		<%= user_form.label :name, "Enter your UserName:" %>
		<%= user_form.text_field :name %>
	</div>
  
	<div> 
		<%= user_form.label :email, "Enter your Email:" %>
		<%= user_form.text_field :email %>
	</div>

	<div> 
		<%= user_form.label :password, "Choose your password:" %>
		<%= user_form.password_field :password%>
	</div>
		

	<div> 
		<%= user_form.label :password_confirmation, "Password confirmation:" %>
  	<%= user_form.password_field :password_confirmation%>
	</div>
	

	<div>
		<%= user_form.submit "Register"  %>	 
	</div>

<% end %>